name: pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  testing:
    name: Run linting, formatter and tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install server dependencies
        run: cd server && npm ci --cache ~/.npm --prefer-offline

      - name: Install client dependencies
        run: cd client && npm ci --cache ~/.npm --prefer-offline

      - name: Install linting dependencies
        run: npm ci --cache ~/.npm --prefer-offline

      - name: Run linter
        run: npm run lint
      
      - name: Run DB tests
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          API_URL: ${{ secrets.API_URL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: cd server && npm run test -- ./src/tests/db/user.test.ts
